import type { Metadata } from "next";
import "./globals.css";
import { aeonik, neueMontreal } from "./fonts";
import Navbar from "./(componenets)/Navbar";
import 'remixicon/fonts/remixicon.css'

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${aeonik.variable} ${neueMontreal.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">{children}</body>
    </html>
  );
}
